//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryBill
    {
        public string idDeliveryBill { get; set; }
        public string idOrder { get; set; }
        public string idAccountant { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string orderStatus { get; set; }
        public string paymentStatus { get; set; }
    
        public virtual accountant accountant { get; set; }
        public virtual order order { get; set; }
    }
}
